# Generated by Django 4.2.1 on 2023-05-31 16:25

from django.db import migrations
import kobosh.models


class Migration(migrations.Migration):

    dependencies = [
        ('kobosh', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=kobosh.models.CommaSeparatedIntegerField(decimal_places=2, max_digits=10),
        ),
    ]
