# Generated by Django 4.2.1 on 2023-06-06 13:07

from django.db import migrations
import kobosh.models


class Migration(migrations.Migration):

    dependencies = [
        ('kobosh', '0009_product_price1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price1',
            new_name='new_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=kobosh.models.CommaSeparatedIntegerField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
