# Generated by Django 4.2.5 on 2023-11-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobosh', '0014_alter_category_image_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
