# Generated by Django 4.2.1 on 2023-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobosh', '0010_rename_price1_product_new_price_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
